version: "3.8"

services:

  cassandra: 
    image: cassandra
    container_name: cassandra
    
    networks:
      - identifi_internal_network
    
    volumes:
      - cassandra-data:/var/lib/cassandra:z
    
    ports:
      - "9042:9042"
      - "9160:9160"

networks:
  identifi_internal_network:
    external: true

volumes:
  cassandra-data:
