version: '3'


services:
  web:
    build: .
    ports:
      - "8000:8000"
    
    # TODO: implement docker secrets or something similar instead of environment variables to enhance security
    environment:
      - COOKIES__HTTPS_ONLY=${COOKIES__HTTPS_ONLY}


      - DB__CASSANDRA__HOSTS=${DB__CASSANDRA__HOSTS}
      - DB__CASSANDRA__KEYSPACE=${DB__CASSANDRA__KEYSPACE}
      - DB__CASSANDRA__PROTOCOL_VERSION=${DB__CASSANDRA__PROTOCOL_VERSION}
      - DB__SCHEMAS__UPDATE=${DB__SCHEMAS__UPDATE}


      - OIDC__EXP_TIME__ACCESS_TOKEN=${OIDC__EXP_TIME__ACCESS_TOKEN}
      - OIDC__EXP_TIME__AUTHCODE=${OIDC__EXP_TIME__AUTHCODE}
      - OIDC__EXP_TIME__ID_TOKEN=${OIDC__EXP_TIME__ID_TOKEN}
      - OIDC__EXP_TIME__REFRESH_TOKEN=${OIDC__EXP_TIME__REFRESH_TOKEN}

      - OIDC__JWE__ALGORITHMS__KEY_MANAGEMENT=${OIDC__JWE__ALGORITHMS__KEY_MANAGEMENT}
      - OIDC__JWE__ALGORITHMS__ENCRYPTION=${OIDC__JWE__ALGORITHMS__ENCRYPTION}
      - OIDC__JWE__SECRET_KEY=${OIDC__JWE__SECRET_KEY}

      - OIDC__JWT__SIGNING_ALGORITHM=${OIDC__JWT__SIGNING_ALGORITHM}
      - OIDC__JWT__KEYS__PRIVATE_KEY=${OIDC__JWT__KEYS__PRIVATE_KEY}
      - OIDC__JWT__KEYS__PUBLIC_KEY=${OIDC__JWT__KEYS__PUBLIC_KEY}


      - SAME_SITE__EXP_TIME__ACCESS_TOKEN=${SAME_SITE__EXP_TIME__ACCESS_TOKEN}
      - SAME_SITE__EXP_TIME__REFRESH_TOKEN=${SAME_SITE__EXP_TIME__REFRESH_TOKEN}

      - SAME_SITE__JWT__SIGNING_ALGORITHM=${SAME_SITE__JWT__SIGNING_ALGORITHM}
      - SAME_SITE__JWT__KEYS__PRIVATE_KEY=${SAME_SITE__JWT__KEYS__PRIVATE_KEY}
      - SAME_SITE__JWT__KEYS__PUBLIC_KEY=${SAME_SITE__JWT__KEYS__PUBLIC_KEY}


      - ISSUER=${ISSUER}
      - LOGIN_ENDPOINT=${LOGIN_ENDPOINT}
      - MAX_SECRET_SIZE_IN_BYTES=${MAX_SECRET_SIZE_IN_BYTES}
